== Web-приложение для получения содержимого удаленного ресурса (+ кэшировнаие)

Написать WEB-приложение c сервлетом|сервлетным фильтром, который осуществляет получение содержимого удалённого ресурса и возвращает его в своём ответе (GET запрос).

Ссылка на ресурс передаётся в параметре url исходного запроса.

Сервлет должен кэшировать результаты успешных запросов (код ответа 2??), и в случае повторного запроса возвращать сохранённый результат.

В ответе должен быть дополнительный заголовок с информацией о дате занесения его в кэш (дате фактического получения ответа с удалённого сервера).

Используйте WeakHashMap в качестве структуры кэша, где URL ключ, а значение - код ответа + заголовки + содержимое.

== REST сервис работы с терминалом

Реализуйте REST сервис работы с терминальным сервером из домашнего задания занятия про Exceptions.
Используйте Spring Web MVC. Верно выбирайте типы запросов и коды состояний HTTP.

_Авторизацию сделала самую базовую с помощью spring-boot-starter-security_